### ISSUE TITLE
Feature-guard cbindgen dependency

### ISSUE THREAD

**Issue by dabreegster** [urschrei/polylabel-rs#1]
I'm having trouble depending on polylabel -- cbindgen 0.6.8 requires the old serde_derive 1.0.58, which is conflicting with the newer version demanded by some of my other dependencies. Is it possible to either guard the build-dependencies section by an optional feature, or upgrade the cbindgen dependency in the hopes that it'll use a more recent serde_derive? Thanks!

**Comment by urschrei** [comment]
Looks like `cbindgen` 0.9.0 is asking for `serde_derive` 1.0.99. Is that recent enough for you?

**Comment by dabreegster** [comment]
Yes, that'd be great if you could push a release with that updated. Thank
you!

**Comment by urschrei** [comment]
👍 v.1.3.0 is on crates.io now.
