### ISSUE TITLE
new release for dependency updates

### ISSUE THREAD

**Issue by michaelkirk** [urschrei/polylabel-rs#27]
It looks like it's only dependency updates, but it'd be nice to avoid patches to avoid including multiple versions of depenencies, e.g. https://github.com/a-b-street/abstreet/blob/master/Cargo.toml#L45

Here are the changes compared to the commit which I think[^**] corresponds to the latest release: https://github.com/urschrei/polylabel-rs/compare/12f0e5e6ed72b590b74138f429a452ab5a44672a...master

[**]Note: We're missing a tag on GH for the latest (2.4.1) release: https://crates.io/crates/polylabel/versions

I'd guess it corresponds to https://github.com/urschrei/polylabel-rs/commit/12f0e5e6ed72b590b74138f429a452ab5a44672a which happened on the same date, but I'm not sure.

**Comment by urschrei** [comment]
@michaelkirk Just to make sure I'm not misunderstanding you:

1. Cut a new release with a patch version bump (2.4.2)
2. Push the v2.4.1 tag for housekeeping purposes

**Comment by michaelkirk** [comment]
Yes, exactly!

**Comment by urschrei** [comment]
- v.2.4.1 and v2.4.2 tags pushed
- [2.4.2 published to crates.io](https://crates.io/crates/polylabel/2.4.2)
