### ISSUE TITLE
Tolerance parameter is too high in example

### ISSUE THREAD

**Issue by bhickey** [urschrei/polylabel-rs#5]
The L-shaped example uses a tolerance of 1.0 yielding the point (0.5, 1.5). Reducing this parameter to 0.1 matches the expected value (0.5625, 0.5625).

Using geo = "0.14.0" and polylabel = "2.3.0"

**Comment by urschrei** [comment]
Where are you seeing the tolerance of `1.0`? It's `0.10` in both [README.md](../blob/master/README.md) and the [notebook](../blob/master/visualise.ipynb).

**Comment by bhickey** [comment]
https://docs.rs/polylabel/2.3.0/polylabel/fn.polylabel.html

**Comment by urschrei** [comment]
🤦‍♂️ doctests were disabled. Fixed in b772e08, published to crates.io and docs.rs as `2.3.1`. Thanks!
